/**
 * Simple API
 * A simple API to illustrate OpenAPI concepts
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Artist model module.
 * @module model/Artist
 * @version 1.0.0
 */
class Artist {
    /**
     * Constructs a new <code>Artist</code>.
     * @alias module:model/Artist
     * @param username {String} 
     */
    constructor(username) { 
        
        Artist.initialize(this, username);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username) { 
        obj['username'] = username;
    }

    /**
     * Constructs a <code>Artist</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Artist} obj Optional instance to populate.
     * @return {module:model/Artist} The populated <code>Artist</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Artist();

            if (data.hasOwnProperty('artist_name')) {
                obj['artist_name'] = ApiClient.convertToType(data['artist_name'], 'String');
            }
            if (data.hasOwnProperty('artist_genre')) {
                obj['artist_genre'] = ApiClient.convertToType(data['artist_genre'], 'String');
            }
            if (data.hasOwnProperty('albums_recorded')) {
                obj['albums_recorded'] = ApiClient.convertToType(data['albums_recorded'], 'Number');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} artist_name
 */
Artist.prototype['artist_name'] = undefined;

/**
 * @member {String} artist_genre
 */
Artist.prototype['artist_genre'] = undefined;

/**
 * @member {Number} albums_recorded
 */
Artist.prototype['albums_recorded'] = undefined;

/**
 * @member {String} username
 */
Artist.prototype['username'] = undefined;






export default Artist;

